nodevault/node-vault

README.md
I think it's ok for the main codebase to be in CoffeeScript but the majority of people using this module are going to be writing javascript so it makes more sense for the examples to be Javascript so they can understand them.
=> Changed examples to javascript

package.json
[Issue 24](https://github.com/kr1sp1n/node-vault/issues/24) details requiring the `node-vault` npm failing because the entry point is a file that no longer exists.
This pull requests updates `main` to `index.js`. As there is no longer a build script I'm assuming this is the correct entry point.
=> Updated npm package main file

src/index.js
This PR adds support for handling errors that do not return an `errors` array (for endpoints and methods that don't return a JSON body at all) and includes the response object as a `response` property of the `Error` object (e.g. for error handling based on specific status codes).
=> Error response improvements

src/index.js
Reference: https://www.vaultproject.io/docs/http/index.html
> You can list secrets as well. To do this, either issue a GET with the query parameter list=true, or you can use the LIST HTTP verb. For the generic backend, listing is allowed on directories only, and returns the keys in the given directory
=> Add list method to enumerate keys of path

src/index.js, test/unit.js
We noticed an issue when attempting to check for an app policy where the app had the word "health" in it.
We were using the getPolicy command to lookup an app to determine whether it had been created and the error condition was not firing, resulting in the app being incorrectly identified as an existing app.
I've provided the solution and a unit test to validate it.
Thanks very much.
=> Paths with "health" in them return the body even on error conditions

src/index.js
The response object includes the request details and can potentially cause Vault tokens to be logged in plain text on insecure systems.
Resolves #50.
=> Don't include request or response body in errors

example/token.js, src/commands.js
Fixes typo on commands entry` tokenLookupAccesspr` to `tokenLookupAccessor`. Adds basic example of token routes as well.
=> Fix typo tokenLookupAccesspr

src/index.js
Fixes #48 `Warning: .then() only accepts functions but was passed: [object Object]`.
Since validate function returns promise, but not a function we need it to wrap into a function.
=> Fix promise chain

Dockerfile
This makes it so `npm install` is only run when `package.json` changes.
=> speed-optmized Dockerfile

features.md, src/commands.js
Per the [Vault documentation on GitHub authentication](https://www.vaultproject.io/api/auth/github/index.html), it is possible to mount auth backends at any location. This PR parameterizes the mount point in the command 
On a related sidenote, the [userpass login function](https://www.vaultproject.io/api/auth/github/index.html#login) requires a password parameter which is not being enforced on the client side.
=> Added support for multiple GitHub mount points and added schema attributes to userpass login function

src/commands.js
Currently unable to renew or revoke database credential leases since the API is incorrectly implemented in node-vault. This change fixes the problem.
This fix was original proposed in kr1sp1n/node-vault#52.
See:
https://www.vaultproject.io/api/system/leases.html#renew-lease
https://www.vaultproject.io/api/system/leases.html#revoke-lease
=> Fix renew and revoke lease

features.md, src/index.js
(check pull request diff)
The condition was malformed in a way that was always returning true. Now it works as I think was originally intended and I also made it more explicit, checking if the token variable contains a string with a length of 1+ characters.
=> Fixed broken token conditional

src/index.js, test/unit.js
This makes it possible to differentiate types of errors based on class rather than by message.
=> Throw custom ApiResponseError for handleVaultResponse

src/commands.js, src/index.js, test/unit.js
**UPDATE**: For now, I've published `@mpareja/node-vault` containing kubernetes login support (PR #92) and support for retaining the received access token (PR #93 - this one).
---
This PR is a configuration driven version of PR #85.
=>  support updating vault token for configured commands

src/index.js, test/unit.js
Currently node-vault uses `options.json` to carry all arguments passed into generated functions. One negative side effect of this... because options.json gets passed into `request`, we end up passing a request body for all GET, DELETE, and others.
For us, this has caused an issue when using Google Cloud Platform, due to the Google Cloud Load Balancer (GCLB) rejecting GET/DELETE calls that have a body. While that is not explicitly against the HTTP spec, this behaviour is also not occurring with the native Vault CLI; only with node-vault.
This patch addresses the issue by only setting request body attributes that are part of the request schema. For non-schema'd functions, it will only set options.json when doing a PUT or a POST.
=> Add request body validation

src/index.js
I have a use-case where I have short lease tokens generated by a userpass auth. I do not want these short lease tokens to be stored in client.token as they will be used quickly and tossed. That said, once those tokens are tossed I have a longer less-privileged token that I want to keep in client.token for most other operations.
This pull-request simply allows the consumer to override the X-Vault-Token for any request.
=> Allow X-Vault-Token header override.

package.json, yarn.lock
This will remove `nsp` dependency and the usage of `nsp` CLI.
The Node Security Platform that was responsible for `nsp` has been acquired by npm, Inc. and the `nsp` service is not working any longer.
=> Remove nsp

features.md, src/commands.js
I've added the Google Cloud login as a supported auth type, per the API documentation here:
https://www.vaultproject.io/api/auth/gcp/index.html#login
Let me know if there's anything else I should add/amend!
=> adding gcp login to auth types

src/commands.js
This PR builds on the work to add kubernetes login support (#92) and the ability to enable some commands to update client tokens (#93). This PR enables updating client tokens as part of the kubernetesLogin command.
=> kubernetesLogin: make it a token source

src/commands.js
It is possible to configure AppRoles to not require a secret_id.
https://www.vaultproject.io/docs/auth/approle.html
https://www.vaultproject.io/api/auth/approle/index.html#create-new-approle
https://www.vaultproject.io/api/auth/approle/index.html#login-with-approle
This PR allows `appRoleLogin()` to be used without `secret_id`. 
Tested locally without issue.
=> secret_id is no longer required

src/index.js
A quick fix for #80, while we wait for v1.0.
Currently, every time you create a vault client, it adds another layer of wrapping to `request` that applies defaults, meaning for every client you create, it adds another frame to the stack when you make a request.
Fixes  #80.
=> fix: Avoid multiple `defaults` wrapping for request.

package.json
Extension of https://github.com/kr1sp1n/node-vault/pull/115
Not sure if index.d.ts needs to be moved to `src/`
Would also need an npm publish/release
=> Ship index.d.ts

src/commands.js
Following up on #93, there are a handful of methods that generate a tokenResponse object but were not marked as `tokenSource` methods.
Selfishly, I'm interested in `/auth/token/renew-self`. But I'm guessing there are others in the community who are interested in the other methods as well.
=> Improve consistency of handling methods that generate tokenResponse objects

src/commands.js
=> approleSecretAccessorLookup() requires parameter 'secret_id_accessor'

src/index.js, test/unit.js
=> feat(vault-namespace): set 'X-Vault-Namespace' when a client has it

features.md, index.d.ts, package.json, src/commands.js
This adds AWS authentication. It uses the IAM method (in vault) specifically not EC2.
Co-Authored-By: Parker Johansen <parker-johansen@pluralsight.com>
Co-Authored-By: Jason Nguyen <jason-nguyen@pluralsight.com>
Co-Authored-By: Wes Novack <wes-novack@pluralsight.com>
=> Add aws authentication using the IAM method

src/index.js
Fixes #179 by creating a variable for each overridden imports inside the instance of VaultClient.
=> Not modifying imports to avoid maximum call stack error, fixes #179

src/index.js, test/unit.js
Per the Vault API, version 1 of the K/V engine supports both PUT and POST methods when creating/updating secrets. But version 2 of the K/V engine only support POST.
This change updates the method used to write data from PUT to POST in order to provide better continuity for the K/V secrets engine, as well as align with other engines (AWS, Azure, GCP, et. al.) that only support POSTs.
=> Changed write method from PUT to POST

features.md, index.d.ts, src/commands.js
Added support for TLS Certificate based Authentication to be able to get the token with client TLS Certificate, as is required according to #206
=> Added support for TLS Certificate based Authentication

.devcontainer/devcontainer.json, README.md
- Improved wording
- Moved links from `kr1sp1n` to `nodevault`; This Will also prevent future repojacking
=> Chore: README updates

README.md, example/auth_kubernetes.js, src/commands.js, src/index.js
kubernetes path can be provided in vault when creating the auth when running a multicluster setup. defaults to kubernetes.
Tested in my test cluster using the new modules and connects to vault and able to retrive data in vault using vault.read after running vault. kubernetesLogin()
=> fix for https://github.com/nodevault/node-vault/issues/143

.github/workflows/lint-and-test.yaml, docker-compose.yml
As seen in https://github.com/nodevault/node-vault/actions/runs/13224738209/job/36914192419?pr=244, `docker-compose` isn't always available on the machine.
Adding the usage of https://github.com/marketplace/actions/docker-compose-action in order to simplify and solve that
=> Fix | Use compose action
